namespace Microservice.Coin.Models;

public class Ath
{
    public double aed { get; set; }
    public double ars { get; set; }
    public double aud { get; set; }
    public double bch { get; set; }
    public double bdt { get; set; }
    public double bhd { get; set; }
    public double bmd { get; set; }
    public double bnb { get; set; }
    public double brl { get; set; }
    public double btc { get; set; }
    public double cad { get; set; }
    public double chf { get; set; }
    public double clp { get; set; }
    public double cny { get; set; }
    public double czk { get; set; }
    public double dkk { get; set; }
    public double dot { get; set; }
    public double eos { get; set; }
    public double eth { get; set; }
    public double eur { get; set; }
    public double gbp { get; set; }
    public double hkd { get; set; }
    public double huf { get; set; }
    public double idr { get; set; }
    public double ils { get; set; }
    public double inr { get; set; }
    public double jpy { get; set; }
    public double krw { get; set; }
    public double kwd { get; set; }
    public double lkr { get; set; }
    public double ltc { get; set; }
    public double mmk { get; set; }
    public double mxn { get; set; }
    public double myr { get; set; }
    public double ngn { get; set; }
    public double nok { get; set; }
    public double nzd { get; set; }
    public double php { get; set; }
    public double pkr { get; set; }
    public double pln { get; set; }
    public double rub { get; set; }
    public double sar { get; set; }
    public double sek { get; set; }
    public double sgd { get; set; }
    public double thb { get; set; }
    public double @try { get; set; }
    public double twd { get; set; }
    public double uah { get; set; }
    public double usd { get; set; }
    public long vef { get; set; }
    public double vnd { get; set; }
    public double xag { get; set; }
    public double xau { get; set; }
    public double xdr { get; set; }
    public double xlm { get; set; }
    public double xrp { get; set; }
    public double yfi { get; set; }
    public double zar { get; set; }
    public double bits { get; set; }
    public double link { get; set; }
    public double sats { get; set; }
}

public class AthChangePercentage
{
    public double aed { get; set; }
    public double ars { get; set; }
    public double aud { get; set; }
    public double bch { get; set; }
    public double bdt { get; set; }
    public double bhd { get; set; }
    public double bmd { get; set; }
    public double bnb { get; set; }
    public double brl { get; set; }
    public double btc { get; set; }
    public double cad { get; set; }
    public double chf { get; set; }
    public double clp { get; set; }
    public double cny { get; set; }
    public double czk { get; set; }
    public double dkk { get; set; }
    public double dot { get; set; }
    public double eos { get; set; }
    public double eth { get; set; }
    public double eur { get; set; }
    public double gbp { get; set; }
    public double hkd { get; set; }
    public double huf { get; set; }
    public double idr { get; set; }
    public double ils { get; set; }
    public double inr { get; set; }
    public double jpy { get; set; }
    public double krw { get; set; }
    public double kwd { get; set; }
    public double lkr { get; set; }
    public double ltc { get; set; }
    public double mmk { get; set; }
    public double mxn { get; set; }
    public double myr { get; set; }
    public double ngn { get; set; }
    public double nok { get; set; }
    public double nzd { get; set; }
    public double php { get; set; }
    public double pkr { get; set; }
    public double pln { get; set; }
    public double rub { get; set; }
    public double sar { get; set; }
    public double sek { get; set; }
    public double sgd { get; set; }
    public double thb { get; set; }
    public double @try { get; set; }
    public double twd { get; set; }
    public double uah { get; set; }
    public double usd { get; set; }
    public double vef { get; set; }
    public double vnd { get; set; }
    public double xag { get; set; }
    public double xau { get; set; }
    public double xdr { get; set; }
    public double xlm { get; set; }
    public double xrp { get; set; }
    public double yfi { get; set; }
    public double zar { get; set; }
    public double bits { get; set; }
    public double link { get; set; }
    public double sats { get; set; }
}

public class AthDate
{
    public DateTime aed { get; set; }
    public DateTime ars { get; set; }
    public DateTime aud { get; set; }
    public DateTime bch { get; set; }
    public DateTime bdt { get; set; }
    public DateTime bhd { get; set; }
    public DateTime bmd { get; set; }
    public DateTime bnb { get; set; }
    public DateTime brl { get; set; }
    public DateTime btc { get; set; }
    public DateTime cad { get; set; }
    public DateTime chf { get; set; }
    public DateTime clp { get; set; }
    public DateTime cny { get; set; }
    public DateTime czk { get; set; }
    public DateTime dkk { get; set; }
    public DateTime dot { get; set; }
    public DateTime eos { get; set; }
    public DateTime eth { get; set; }
    public DateTime eur { get; set; }
    public DateTime gbp { get; set; }
    public DateTime hkd { get; set; }
    public DateTime huf { get; set; }
    public DateTime idr { get; set; }
    public DateTime ils { get; set; }
    public DateTime inr { get; set; }
    public DateTime jpy { get; set; }
    public DateTime krw { get; set; }
    public DateTime kwd { get; set; }
    public DateTime lkr { get; set; }
    public DateTime ltc { get; set; }
    public DateTime mmk { get; set; }
    public DateTime mxn { get; set; }
    public DateTime myr { get; set; }
    public DateTime ngn { get; set; }
    public DateTime nok { get; set; }
    public DateTime nzd { get; set; }
    public DateTime php { get; set; }
    public DateTime pkr { get; set; }
    public DateTime pln { get; set; }
    public DateTime rub { get; set; }
    public DateTime sar { get; set; }
    public DateTime sek { get; set; }
    public DateTime sgd { get; set; }
    public DateTime thb { get; set; }
    public DateTime @try { get; set; }
    public DateTime twd { get; set; }
    public DateTime uah { get; set; }
    public DateTime usd { get; set; }
    public DateTime vef { get; set; }
    public DateTime vnd { get; set; }
    public DateTime xag { get; set; }
    public DateTime xau { get; set; }
    public DateTime xdr { get; set; }
    public DateTime xlm { get; set; }
    public DateTime xrp { get; set; }
    public DateTime yfi { get; set; }
    public DateTime zar { get; set; }
    public DateTime bits { get; set; }
    public DateTime link { get; set; }
    public DateTime sats { get; set; }
}

public class Atl
{
    public double aed { get; set; }
    public double ars { get; set; }
    public double aud { get; set; }
    public double bch { get; set; }
    public double bdt { get; set; }
    public double bhd { get; set; }
    public double bmd { get; set; }
    public double bnb { get; set; }
    public double brl { get; set; }
    public double btc { get; set; }
    public double cad { get; set; }
    public double chf { get; set; }
    public double clp { get; set; }
    public double cny { get; set; }
    public double czk { get; set; }
    public double dkk { get; set; }
    public double dot { get; set; }
    public double eos { get; set; }
    public double eth { get; set; }
    public double eur { get; set; }
    public double gbp { get; set; }
    public double hkd { get; set; }
    public double huf { get; set; }
    public double idr { get; set; }
    public double ils { get; set; }
    public double inr { get; set; }
    public double jpy { get; set; }
    public double krw { get; set; }
    public double kwd { get; set; }
    public double lkr { get; set; }
    public double ltc { get; set; }
    public double mmk { get; set; }
    public double mxn { get; set; }
    public double myr { get; set; }
    public double ngn { get; set; }
    public double nok { get; set; }
    public double nzd { get; set; }
    public double php { get; set; }
    public double pkr { get; set; }
    public double pln { get; set; }
    public double rub { get; set; }
    public double sar { get; set; }
    public double sek { get; set; }
    public double sgd { get; set; }
    public double thb { get; set; }
    public double @try { get; set; }
    public double twd { get; set; }
    public double uah { get; set; }
    public double usd { get; set; }
    public double vef { get; set; }
    public double vnd { get; set; }
    public double xag { get; set; }
    public double xau { get; set; }
    public double xdr { get; set; }
    public double xlm { get; set; }
    public double xrp { get; set; }
    public double yfi { get; set; }
    public double zar { get; set; }
    public double bits { get; set; }
    public double link { get; set; }
    public double sats { get; set; }
}

public class AtlChangePercentage
{
    public double aed { get; set; }
    public double ars { get; set; }
    public double aud { get; set; }
    public double bch { get; set; }
    public double bdt { get; set; }
    public double bhd { get; set; }
    public double bmd { get; set; }
    public double bnb { get; set; }
    public double brl { get; set; }
    public double btc { get; set; }
    public double cad { get; set; }
    public double chf { get; set; }
    public double clp { get; set; }
    public double cny { get; set; }
    public double czk { get; set; }
    public double dkk { get; set; }
    public double dot { get; set; }
    public double eos { get; set; }
    public double eth { get; set; }
    public double eur { get; set; }
    public double gbp { get; set; }
    public double hkd { get; set; }
    public double huf { get; set; }
    public double idr { get; set; }
    public double ils { get; set; }
    public double inr { get; set; }
    public double jpy { get; set; }
    public double krw { get; set; }
    public double kwd { get; set; }
    public double lkr { get; set; }
    public double ltc { get; set; }
    public double mmk { get; set; }
    public double mxn { get; set; }
    public double myr { get; set; }
    public double ngn { get; set; }
    public double nok { get; set; }
    public double nzd { get; set; }
    public double php { get; set; }
    public double pkr { get; set; }
    public double pln { get; set; }
    public double rub { get; set; }
    public double sar { get; set; }
    public double sek { get; set; }
    public double sgd { get; set; }
    public double thb { get; set; }
    public double @try { get; set; }
    public double twd { get; set; }
    public double uah { get; set; }
    public double usd { get; set; }
    public double vef { get; set; }
    public double vnd { get; set; }
    public double xag { get; set; }
    public double xau { get; set; }
    public double xdr { get; set; }
    public double xlm { get; set; }
    public double xrp { get; set; }
    public double yfi { get; set; }
    public double zar { get; set; }
    public double bits { get; set; }
    public double link { get; set; }
    public double sats { get; set; }
}

public class AtlDate
{
    public DateTime aed { get; set; }
    public DateTime ars { get; set; }
    public DateTime aud { get; set; }
    public DateTime bch { get; set; }
    public DateTime bdt { get; set; }
    public DateTime bhd { get; set; }
    public DateTime bmd { get; set; }
    public DateTime bnb { get; set; }
    public DateTime brl { get; set; }
    public DateTime btc { get; set; }
    public DateTime cad { get; set; }
    public DateTime chf { get; set; }
    public DateTime clp { get; set; }
    public DateTime cny { get; set; }
    public DateTime czk { get; set; }
    public DateTime dkk { get; set; }
    public DateTime dot { get; set; }
    public DateTime eos { get; set; }
    public DateTime eth { get; set; }
    public DateTime eur { get; set; }
    public DateTime gbp { get; set; }
    public DateTime hkd { get; set; }
    public DateTime huf { get; set; }
    public DateTime idr { get; set; }
    public DateTime ils { get; set; }
    public DateTime inr { get; set; }
    public DateTime jpy { get; set; }
    public DateTime krw { get; set; }
    public DateTime kwd { get; set; }
    public DateTime lkr { get; set; }
    public DateTime ltc { get; set; }
    public DateTime mmk { get; set; }
    public DateTime mxn { get; set; }
    public DateTime myr { get; set; }
    public DateTime ngn { get; set; }
    public DateTime nok { get; set; }
    public DateTime nzd { get; set; }
    public DateTime php { get; set; }
    public DateTime pkr { get; set; }
    public DateTime pln { get; set; }
    public DateTime rub { get; set; }
    public DateTime sar { get; set; }
    public DateTime sek { get; set; }
    public DateTime sgd { get; set; }
    public DateTime thb { get; set; }
    public DateTime @try { get; set; }
    public DateTime twd { get; set; }
    public DateTime uah { get; set; }
    public DateTime usd { get; set; }
    public DateTime vef { get; set; }
    public DateTime vnd { get; set; }
    public DateTime xag { get; set; }
    public DateTime xau { get; set; }
    public DateTime xdr { get; set; }
    public DateTime xlm { get; set; }
    public DateTime xrp { get; set; }
    public DateTime yfi { get; set; }
    public DateTime zar { get; set; }
    public DateTime bits { get; set; }
    public DateTime link { get; set; }
    public DateTime sats { get; set; }
}

public class CurrentPrice
{
    public double aed { get; set; }
    public double ars { get; set; }
    public double aud { get; set; }
    public double bch { get; set; }
    public double bdt { get; set; }
    public double bhd { get; set; }
    public double bmd { get; set; }
    public double bnb { get; set; }
    public double brl { get; set; }
    public double btc { get; set; }
    public double cad { get; set; }
    public double chf { get; set; }
    public double clp { get; set; }
    public double cny { get; set; }
    public double czk { get; set; }
    public double dkk { get; set; }
    public double dot { get; set; }
    public double eos { get; set; }
    public double eth { get; set; }
    public double eur { get; set; }
    public double gbp { get; set; }
    public double hkd { get; set; }
    public double huf { get; set; }
    public double idr { get; set; }
    public double ils { get; set; }
    public double inr { get; set; }
    public double jpy { get; set; }
    public double krw { get; set; }
    public double kwd { get; set; }
    public double lkr { get; set; }
    public double ltc { get; set; }
    public double mmk { get; set; }
    public double mxn { get; set; }
    public double myr { get; set; }
    public double ngn { get; set; }
    public double nok { get; set; }
    public double nzd { get; set; }
    public double php { get; set; }
    public double pkr { get; set; }
    public double pln { get; set; }
    public double rub { get; set; }
    public double sar { get; set; }
    public double sek { get; set; }
    public double sgd { get; set; }
    public double thb { get; set; }
    public double @try { get; set; }
    public double twd { get; set; }
    public double uah { get; set; }
    public double usd { get; set; }
    public double vef { get; set; }
    public double vnd { get; set; }
    public double xag { get; set; }
    public double xau { get; set; }
    public double xdr { get; set; }
    public double xlm { get; set; }
    public double xrp { get; set; }
    public double yfi { get; set; }
    public double zar { get; set; }
    public double bits { get; set; }
    public double link { get; set; }
    public double sats { get; set; }
}

public class Description
{
    public string en { get; set; }
}

public class FullyDilutedValuation
{
    public long aed { get; set; }
    public long ars { get; set; }
    public long aud { get; set; }
    public long bch { get; set; }
    public long bdt { get; set; }
    public long bhd { get; set; }
    public long bmd { get; set; }
    public double bnb { get; set; }
    public long brl { get; set; }
    public double btc { get; set; }
    public long cad { get; set; }
    public long chf { get; set; }
    public long clp { get; set; }
    public long cny { get; set; }
    public long czk { get; set; }
    public long dkk { get; set; }
    public long dot { get; set; }
    public long eos { get; set; }
    public double eth { get; set; }
    public long eur { get; set; }
    public long gbp { get; set; }
    public long hkd { get; set; }
    public long huf { get; set; }
    public long idr { get; set; }
    public long ils { get; set; }
    public long inr { get; set; }
    public long jpy { get; set; }
    public long krw { get; set; }
    public long kwd { get; set; }
    public long lkr { get; set; }
    public long ltc { get; set; }
    public long mmk { get; set; }
    public long mxn { get; set; }
    public long myr { get; set; }
    public long ngn { get; set; }
    public long nok { get; set; }
    public long nzd { get; set; }
    public long php { get; set; }
    public long pkr { get; set; }
    public long pln { get; set; }
    public long rub { get; set; }
    public long sar { get; set; }
    public long sek { get; set; }
    public long sgd { get; set; }
    public long thb { get; set; }
    public long @try { get; set; }
    public long twd { get; set; }
    public long uah { get; set; }
    public long usd { get; set; }
    public long vef { get; set; }
    public long vnd { get; set; }
    public long xag { get; set; }
    public double xau { get; set; }
    public long xdr { get; set; }
    public long xlm { get; set; }
    public long xrp { get; set; }
    public double yfi { get; set; }
    public long zar { get; set; }
    public long bits { get; set; }
    public long link { get; set; }
    public long sats { get; set; }
}

public class High24h
{
    public double aed { get; set; }
    public double ars { get; set; }
    public double aud { get; set; }
    public double bch { get; set; }
    public double bdt { get; set; }
    public double bhd { get; set; }
    public double bmd { get; set; }
    public double bnb { get; set; }
    public double brl { get; set; }
    public double btc { get; set; }
    public double cad { get; set; }
    public double chf { get; set; }
    public double clp { get; set; }
    public double cny { get; set; }
    public double czk { get; set; }
    public double dkk { get; set; }
    public double dot { get; set; }
    public double eos { get; set; }
    public double eth { get; set; }
    public double eur { get; set; }
    public double gbp { get; set; }
    public double hkd { get; set; }
    public double huf { get; set; }
    public double idr { get; set; }
    public double ils { get; set; }
    public double inr { get; set; }
    public double jpy { get; set; }
    public double krw { get; set; }
    public double kwd { get; set; }
    public double lkr { get; set; }
    public double ltc { get; set; }
    public double mmk { get; set; }
    public double mxn { get; set; }
    public double myr { get; set; }
    public double ngn { get; set; }
    public double nok { get; set; }
    public double nzd { get; set; }
    public double php { get; set; }
    public double pkr { get; set; }
    public double pln { get; set; }
    public double rub { get; set; }
    public double sar { get; set; }
    public double sek { get; set; }
    public double sgd { get; set; }
    public double thb { get; set; }
    public double @try { get; set; }
    public double twd { get; set; }
    public double uah { get; set; }
    public double usd { get; set; }
    public double vef { get; set; }
    public double vnd { get; set; }
    public double xag { get; set; }
    public double xau { get; set; }
    public double xdr { get; set; }
    public double xlm { get; set; }
    public double xrp { get; set; }
    public double yfi { get; set; }
    public double zar { get; set; }
    public double bits { get; set; }
    public double link { get; set; }
    public double sats { get; set; }
}

public class Image
{
    public string thumb { get; set; }
    public string small { get; set; }
    public string large { get; set; }
}

public class Links
{
    public List<string> homepage { get; set; }
    public List<string> blockchain_site { get; set; }
    public List<string> official_forum_url { get; set; }
    public List<string> chat_url { get; set; }
    public List<string> announcement_url { get; set; }
    public string twitter_screen_name { get; set; }
    public string facebook_username { get; set; }
    public object bitcodoublealk_thread_identifier { get; set; }
    public string telegram_channel_identifier { get; set; }
    public string subreddit_url { get; set; }
    public ReposUrl repos_url { get; set; }
}

public class Low24h
{
    public double aed { get; set; }
    public double ars { get; set; }
    public double aud { get; set; }
    public double bch { get; set; }
    public double bdt { get; set; }
    public double bhd { get; set; }
    public double bmd { get; set; }
    public double bnb { get; set; }
    public double brl { get; set; }
    public double btc { get; set; }
    public double cad { get; set; }
    public double chf { get; set; }
    public double clp { get; set; }
    public double cny { get; set; }
    public double czk { get; set; }
    public double dkk { get; set; }
    public double dot { get; set; }
    public double eos { get; set; }
    public double eth { get; set; }
    public double eur { get; set; }
    public double gbp { get; set; }
    public double hkd { get; set; }
    public double huf { get; set; }
    public double idr { get; set; }
    public double ils { get; set; }
    public double inr { get; set; }
    public double jpy { get; set; }
    public double krw { get; set; }
    public double kwd { get; set; }
    public double lkr { get; set; }
    public double ltc { get; set; }
    public double mmk { get; set; }
    public double mxn { get; set; }
    public double myr { get; set; }
    public double ngn { get; set; }
    public double nok { get; set; }
    public double nzd { get; set; }
    public double php { get; set; }
    public double pkr { get; set; }
    public double pln { get; set; }
    public double rub { get; set; }
    public double sar { get; set; }
    public double sek { get; set; }
    public double sgd { get; set; }
    public double thb { get; set; }
    public double @try { get; set; }
    public double twd { get; set; }
    public double uah { get; set; }
    public double usd { get; set; }
    public double vef { get; set; }
    public double vnd { get; set; }
    public double xag { get; set; }
    public double xau { get; set; }
    public double xdr { get; set; }
    public double xlm { get; set; }
    public double xrp { get; set; }
    public double yfi { get; set; }
    public double zar { get; set; }
    public double bits { get; set; }
    public double link { get; set; }
    public double sats { get; set; }
}

public class MarketCap
{
    public long aed { get; set; }
    public long ars { get; set; }
    public long aud { get; set; }
    public long bch { get; set; }
    public long bdt { get; set; }
    public long bhd { get; set; }
    public long bmd { get; set; }
    public double bnb { get; set; }
    public long brl { get; set; }
    public double btc { get; set; }
    public long cad { get; set; }
    public long chf { get; set; }
    public long clp { get; set; }
    public long cny { get; set; }
    public long czk { get; set; }
    public long dkk { get; set; }
    public long dot { get; set; }
    public long eos { get; set; }
    public double eth { get; set; }
    public long eur { get; set; }
    public long gbp { get; set; }
    public long hkd { get; set; }
    public long huf { get; set; }
    public long idr { get; set; }
    public long ils { get; set; }
    public long inr { get; set; }
    public long jpy { get; set; }
    public long krw { get; set; }
    public long kwd { get; set; }
    public long lkr { get; set; }
    public long ltc { get; set; }
    public long mmk { get; set; }
    public long mxn { get; set; }
    public long myr { get; set; }
    public long ngn { get; set; }
    public long nok { get; set; }
    public long nzd { get; set; }
    public long php { get; set; }
    public long pkr { get; set; }
    public long pln { get; set; }
    public long rub { get; set; }
    public long sar { get; set; }
    public long sek { get; set; }
    public long sgd { get; set; }
    public long thb { get; set; }
    public long @try { get; set; }
    public long twd { get; set; }
    public long uah { get; set; }
    public long usd { get; set; }
    public long vef { get; set; }
    public long vnd { get; set; }
    public long xag { get; set; }
    public double xau { get; set; }
    public long xdr { get; set; }
    public long xlm { get; set; }
    public long xrp { get; set; }
    public double yfi { get; set; }
    public long zar { get; set; }
    public long bits { get; set; }
    public long link { get; set; }
    public long sats { get; set; }
}

public class MarketCapChange24hInCurrency
{
    public double aed { get; set; }
    public double ars { get; set; }
    public double aud { get; set; }
    public double bch { get; set; }
    public double bdt { get; set; }
    public double bhd { get; set; }
    public double bmd { get; set; }
    public double bnb { get; set; }
    public double brl { get; set; }
    public double btc { get; set; }
    public double cad { get; set; }
    public double chf { get; set; }
    public double clp { get; set; }
    public double cny { get; set; }
    public double czk { get; set; }
    public double dkk { get; set; }
    public double dot { get; set; }
    public long eos { get; set; }
    public double eth { get; set; }
    public double eur { get; set; }
    public double gbp { get; set; }
    public double hkd { get; set; }
    public double huf { get; set; }
    public double idr { get; set; }
    public double ils { get; set; }
    public double inr { get; set; }
    public double jpy { get; set; }
    public double krw { get; set; }
    public double kwd { get; set; }
    public double lkr { get; set; }
    public double ltc { get; set; }
    public double mmk { get; set; }
    public double mxn { get; set; }
    public double myr { get; set; }
    public double ngn { get; set; }
    public double nok { get; set; }
    public double nzd { get; set; }
    public double php { get; set; }
    public double pkr { get; set; }
    public double pln { get; set; }
    public double rub { get; set; }
    public double sar { get; set; }
    public double sek { get; set; }
    public double sgd { get; set; }
    public double thb { get; set; }
    public double @try { get; set; }
    public double twd { get; set; }
    public double uah { get; set; }
    public double usd { get; set; }
    public double vef { get; set; }
    public double vnd { get; set; }
    public double xag { get; set; }
    public double xau { get; set; }
    public double xdr { get; set; }
    public long xlm { get; set; }
    public long xrp { get; set; }
    public double yfi { get; set; }
    public double zar { get; set; }
    public long bits { get; set; }
    public double link { get; set; }
    public long sats { get; set; }
}

public class MarketCapChangePercentage24hInCurrency
{
    public double aed { get; set; }
    public double ars { get; set; }
    public double aud { get; set; }
    public double bch { get; set; }
    public double bdt { get; set; }
    public double bhd { get; set; }
    public double bmd { get; set; }
    public double bnb { get; set; }
    public double brl { get; set; }
    public double btc { get; set; }
    public double cad { get; set; }
    public double chf { get; set; }
    public double clp { get; set; }
    public double cny { get; set; }
    public double czk { get; set; }
    public double dkk { get; set; }
    public double dot { get; set; }
    public double eos { get; set; }
    public double eth { get; set; }
    public double eur { get; set; }
    public double gbp { get; set; }
    public double hkd { get; set; }
    public double huf { get; set; }
    public double idr { get; set; }
    public double ils { get; set; }
    public double inr { get; set; }
    public double jpy { get; set; }
    public double krw { get; set; }
    public double kwd { get; set; }
    public double lkr { get; set; }
    public double ltc { get; set; }
    public double mmk { get; set; }
    public double mxn { get; set; }
    public double myr { get; set; }
    public double ngn { get; set; }
    public double nok { get; set; }
    public double nzd { get; set; }
    public double php { get; set; }
    public double pkr { get; set; }
    public double pln { get; set; }
    public double rub { get; set; }
    public double sar { get; set; }
    public double sek { get; set; }
    public double sgd { get; set; }
    public double thb { get; set; }
    public double @try { get; set; }
    public double twd { get; set; }
    public double uah { get; set; }
    public double usd { get; set; }
    public double vef { get; set; }
    public double vnd { get; set; }
    public double xag { get; set; }
    public double xau { get; set; }
    public double xdr { get; set; }
    public double xlm { get; set; }
    public double xrp { get; set; }
    public double yfi { get; set; }
    public double zar { get; set; }
    public double bits { get; set; }
    public double link { get; set; }
    public double sats { get; set; }
}

public class MarketData
{
    public CurrentPrice current_price { get; set; }
    public object total_value_locked { get; set; }
    public object mcap_to_tvl_ratio { get; set; }
    public object fdv_to_tvl_ratio { get; set; }
    public object roi { get; set; }
    public Ath ath { get; set; }
    public AthChangePercentage ath_change_percentage { get; set; }
    public AthDate ath_date { get; set; }
    public Atl atl { get; set; }
    public AtlChangePercentage atl_change_percentage { get; set; }
    public AtlDate atl_date { get; set; }
    public MarketCap market_cap { get; set; }
    public double market_cap_rank { get; set; }
    public FullyDilutedValuation fully_diluted_valuation { get; set; }
    public TotalVolume total_volume { get; set; }
    public High24h high_24h { get; set; }
    public Low24h low_24h { get; set; }
    public double price_change_24h { get; set; }
    public double price_change_percentage_24h { get; set; }
    public double price_change_percentage_7d { get; set; }
    public double price_change_percentage_14d { get; set; }
    public double price_change_percentage_30d { get; set; }
    public double price_change_percentage_60d { get; set; }
    public double price_change_percentage_200d { get; set; }
    public double price_change_percentage_1y { get; set; }
    public double market_cap_change_24h { get; set; }
    public double market_cap_change_percentage_24h { get; set; }
    public PriceChange24hInCurrency price_change_24h_in_currency { get; set; }
    public PriceChangePercentage1hInCurrency price_change_percentage_1h_in_currency { get; set; }
    public PriceChangePercentage24hInCurrency price_change_percentage_24h_in_currency { get; set; }
    public PriceChangePercentage7dInCurrency price_change_percentage_7d_in_currency { get; set; }
    public PriceChangePercentage14dInCurrency price_change_percentage_14d_in_currency { get; set; }
    public PriceChangePercentage30dInCurrency price_change_percentage_30d_in_currency { get; set; }
    public PriceChangePercentage60dInCurrency price_change_percentage_60d_in_currency { get; set; }
    public PriceChangePercentage200dInCurrency price_change_percentage_200d_in_currency { get; set; }
    public PriceChangePercentage1yInCurrency price_change_percentage_1y_in_currency { get; set; }
    public MarketCapChange24hInCurrency market_cap_change_24h_in_currency { get; set; }
    public MarketCapChangePercentage24hInCurrency market_cap_change_percentage_24h_in_currency { get; set; }
    public double total_supply { get; set; }
    public double max_supply { get; set; }
    public double circulating_supply { get; set; }
    public DateTime last_updated { get; set; }
}

public class Platforms
{
    
}

    public class PriceChange24hInCurrency
{
    public double aed { get; set; }
    public double ars { get; set; }
    public double aud { get; set; }
    public double bch { get; set; }
    public double bdt { get; set; }
    public double bhd { get; set; }
    public double bmd { get; set; }
    public double bnb { get; set; }
    public double brl { get; set; }
    public double btc { get; set; }
    public double cad { get; set; }
    public double chf { get; set; }
    public double clp { get; set; }
    public double cny { get; set; }
    public double czk { get; set; }
    public double dkk { get; set; }
    public double dot { get; set; }
    public double eos { get; set; }
    public double eth { get; set; }
    public double eur { get; set; }
    public double gbp { get; set; }
    public double hkd { get; set; }
    public double huf { get; set; }
    public double idr { get; set; }
    public double ils { get; set; }
    public double inr { get; set; }
    public double jpy { get; set; }
    public double krw { get; set; }
    public double kwd { get; set; }
    public double lkr { get; set; }
    public double ltc { get; set; }
    public double mmk { get; set; }
    public double mxn { get; set; }
    public double myr { get; set; }
    public double ngn { get; set; }
    public double nok { get; set; }
    public double nzd { get; set; }
    public double php { get; set; }
    public double pkr { get; set; }
    public double pln { get; set; }
    public double rub { get; set; }
    public double sar { get; set; }
    public double sek { get; set; }
    public double sgd { get; set; }
    public double thb { get; set; }
    public double @try { get; set; }
    public double twd { get; set; }
    public double uah { get; set; }
    public double usd { get; set; }
    public double vef { get; set; }
    public double vnd { get; set; }
    public double xag { get; set; }
    public double xau { get; set; }
    public double xdr { get; set; }
    public double xlm { get; set; }
    public double xrp { get; set; }
    public double yfi { get; set; }
    public double zar { get; set; }
    public double bits { get; set; }
    public double link { get; set; }
    public double sats { get; set; }
}

public class PriceChangePercentage14dInCurrency
{
    public double aed { get; set; }
    public double ars { get; set; }
    public double aud { get; set; }
    public double bch { get; set; }
    public double bdt { get; set; }
    public double bhd { get; set; }
    public double bmd { get; set; }
    public double bnb { get; set; }
    public double brl { get; set; }
    public double btc { get; set; }
    public double cad { get; set; }
    public double chf { get; set; }
    public double clp { get; set; }
    public double cny { get; set; }
    public double czk { get; set; }
    public double dkk { get; set; }
    public double dot { get; set; }
    public double eos { get; set; }
    public double eth { get; set; }
    public double eur { get; set; }
    public double gbp { get; set; }
    public double hkd { get; set; }
    public double huf { get; set; }
    public double idr { get; set; }
    public double ils { get; set; }
    public double inr { get; set; }
    public double jpy { get; set; }
    public double krw { get; set; }
    public double kwd { get; set; }
    public double lkr { get; set; }
    public double ltc { get; set; }
    public double mmk { get; set; }
    public double mxn { get; set; }
    public double myr { get; set; }
    public double ngn { get; set; }
    public double nok { get; set; }
    public double nzd { get; set; }
    public double php { get; set; }
    public double pkr { get; set; }
    public double pln { get; set; }
    public double rub { get; set; }
    public double sar { get; set; }
    public double sek { get; set; }
    public double sgd { get; set; }
    public double thb { get; set; }
    public double @try { get; set; }
    public double twd { get; set; }
    public double uah { get; set; }
    public double usd { get; set; }
    public double vef { get; set; }
    public double vnd { get; set; }
    public double xag { get; set; }
    public double xau { get; set; }
    public double xdr { get; set; }
    public double xlm { get; set; }
    public double xrp { get; set; }
    public double yfi { get; set; }
    public double zar { get; set; }
    public double bits { get; set; }
    public double link { get; set; }
    public double sats { get; set; }
}

public class PriceChangePercentage1hInCurrency
{
    public double aed { get; set; }
    public double ars { get; set; }
    public double aud { get; set; }
    public double bch { get; set; }
    public double bdt { get; set; }
    public double bhd { get; set; }
    public double bmd { get; set; }
    public double bnb { get; set; }
    public double brl { get; set; }
    public double btc { get; set; }
    public double cad { get; set; }
    public double chf { get; set; }
    public double clp { get; set; }
    public double cny { get; set; }
    public double czk { get; set; }
    public double dkk { get; set; }
    public double dot { get; set; }
    public double eos { get; set; }
    public double eth { get; set; }
    public double eur { get; set; }
    public double gbp { get; set; }
    public double hkd { get; set; }
    public double huf { get; set; }
    public double idr { get; set; }
    public double ils { get; set; }
    public double inr { get; set; }
    public double jpy { get; set; }
    public double krw { get; set; }
    public double kwd { get; set; }
    public double lkr { get; set; }
    public double ltc { get; set; }
    public double mmk { get; set; }
    public double mxn { get; set; }
    public double myr { get; set; }
    public double ngn { get; set; }
    public double nok { get; set; }
    public double nzd { get; set; }
    public double php { get; set; }
    public double pkr { get; set; }
    public double pln { get; set; }
    public double rub { get; set; }
    public double sar { get; set; }
    public double sek { get; set; }
    public double sgd { get; set; }
    public double thb { get; set; }
    public double @try { get; set; }
    public double twd { get; set; }
    public double uah { get; set; }
    public double usd { get; set; }
    public double vef { get; set; }
    public double vnd { get; set; }
    public double xag { get; set; }
    public double xau { get; set; }
    public double xdr { get; set; }
    public double xlm { get; set; }
    public double xrp { get; set; }
    public double yfi { get; set; }
    public double zar { get; set; }
    public double bits { get; set; }
    public double link { get; set; }
    public double sats { get; set; }
}

public class PriceChangePercentage1yInCurrency
{
    public double aed { get; set; }
    public double ars { get; set; }
    public double aud { get; set; }
    public double bch { get; set; }
    public double bdt { get; set; }
    public double bhd { get; set; }
    public double bmd { get; set; }
    public double bnb { get; set; }
    public double brl { get; set; }
    public double btc { get; set; }
    public double cad { get; set; }
    public double chf { get; set; }
    public double clp { get; set; }
    public double cny { get; set; }
    public double czk { get; set; }
    public double dkk { get; set; }
    public double dot { get; set; }
    public double eos { get; set; }
    public double eth { get; set; }
    public double eur { get; set; }
    public double gbp { get; set; }
    public double hkd { get; set; }
    public double huf { get; set; }
    public double idr { get; set; }
    public double ils { get; set; }
    public double inr { get; set; }
    public double jpy { get; set; }
    public double krw { get; set; }
    public double kwd { get; set; }
    public double lkr { get; set; }
    public double ltc { get; set; }
    public double mmk { get; set; }
    public double mxn { get; set; }
    public double myr { get; set; }
    public double ngn { get; set; }
    public double nok { get; set; }
    public double nzd { get; set; }
    public double php { get; set; }
    public double pkr { get; set; }
    public double pln { get; set; }
    public double rub { get; set; }
    public double sar { get; set; }
    public double sek { get; set; }
    public double sgd { get; set; }
    public double thb { get; set; }
    public double @try { get; set; }
    public double twd { get; set; }
    public double uah { get; set; }
    public double usd { get; set; }
    public double vef { get; set; }
    public double vnd { get; set; }
    public double xag { get; set; }
    public double xau { get; set; }
    public double xdr { get; set; }
    public double xlm { get; set; }
    public double xrp { get; set; }
    public double yfi { get; set; }
    public double zar { get; set; }
    public double bits { get; set; }
    public double link { get; set; }
    public double sats { get; set; }
}

public class PriceChangePercentage200dInCurrency
{
    public double aed { get; set; }
    public double ars { get; set; }
    public double aud { get; set; }
    public double bch { get; set; }
    public double bdt { get; set; }
    public double bhd { get; set; }
    public double bmd { get; set; }
    public double bnb { get; set; }
    public double brl { get; set; }
    public double btc { get; set; }
    public double cad { get; set; }
    public double chf { get; set; }
    public double clp { get; set; }
    public double cny { get; set; }
    public double czk { get; set; }
    public double dkk { get; set; }
    public double dot { get; set; }
    public double eos { get; set; }
    public double eth { get; set; }
    public double eur { get; set; }
    public double gbp { get; set; }
    public double hkd { get; set; }
    public double huf { get; set; }
    public double idr { get; set; }
    public double ils { get; set; }
    public double inr { get; set; }
    public double jpy { get; set; }
    public double krw { get; set; }
    public double kwd { get; set; }
    public double lkr { get; set; }
    public double ltc { get; set; }
    public double mmk { get; set; }
    public double mxn { get; set; }
    public double myr { get; set; }
    public double ngn { get; set; }
    public double nok { get; set; }
    public double nzd { get; set; }
    public double php { get; set; }
    public double pkr { get; set; }
    public double pln { get; set; }
    public double rub { get; set; }
    public double sar { get; set; }
    public double sek { get; set; }
    public double sgd { get; set; }
    public double thb { get; set; }
    public double @try { get; set; }
    public double twd { get; set; }
    public double uah { get; set; }
    public double usd { get; set; }
    public double vef { get; set; }
    public double vnd { get; set; }
    public double xag { get; set; }
    public double xau { get; set; }
    public double xdr { get; set; }
    public double xlm { get; set; }
    public double xrp { get; set; }
    public double yfi { get; set; }
    public double zar { get; set; }
    public double bits { get; set; }
    public double link { get; set; }
    public double sats { get; set; }
}

public class PriceChangePercentage24hInCurrency
{
    public double aed { get; set; }
    public double ars { get; set; }
    public double aud { get; set; }
    public double bch { get; set; }
    public double bdt { get; set; }
    public double bhd { get; set; }
    public double bmd { get; set; }
    public double bnb { get; set; }
    public double brl { get; set; }
    public double btc { get; set; }
    public double cad { get; set; }
    public double chf { get; set; }
    public double clp { get; set; }
    public double cny { get; set; }
    public double czk { get; set; }
    public double dkk { get; set; }
    public double dot { get; set; }
    public double eos { get; set; }
    public double eth { get; set; }
    public double eur { get; set; }
    public double gbp { get; set; }
    public double hkd { get; set; }
    public double huf { get; set; }
    public double idr { get; set; }
    public double ils { get; set; }
    public double inr { get; set; }
    public double jpy { get; set; }
    public double krw { get; set; }
    public double kwd { get; set; }
    public double lkr { get; set; }
    public double ltc { get; set; }
    public double mmk { get; set; }
    public double mxn { get; set; }
    public double myr { get; set; }
    public double ngn { get; set; }
    public double nok { get; set; }
    public double nzd { get; set; }
    public double php { get; set; }
    public double pkr { get; set; }
    public double pln { get; set; }
    public double rub { get; set; }
    public double sar { get; set; }
    public double sek { get; set; }
    public double sgd { get; set; }
    public double thb { get; set; }
    public double @try { get; set; }
    public double twd { get; set; }
    public double uah { get; set; }
    public double usd { get; set; }
    public double vef { get; set; }
    public double vnd { get; set; }
    public double xag { get; set; }
    public double xau { get; set; }
    public double xdr { get; set; }
    public double xlm { get; set; }
    public double xrp { get; set; }
    public double yfi { get; set; }
    public double zar { get; set; }
    public double bits { get; set; }
    public double link { get; set; }
    public double sats { get; set; }
}

public class PriceChangePercentage30dInCurrency
{
    public double aed { get; set; }
    public double ars { get; set; }
    public double aud { get; set; }
    public double bch { get; set; }
    public double bdt { get; set; }
    public double bhd { get; set; }
    public double bmd { get; set; }
    public double bnb { get; set; }
    public double brl { get; set; }
    public double btc { get; set; }
    public double cad { get; set; }
    public double chf { get; set; }
    public double clp { get; set; }
    public double cny { get; set; }
    public double czk { get; set; }
    public double dkk { get; set; }
    public double dot { get; set; }
    public double eos { get; set; }
    public double eth { get; set; }
    public double eur { get; set; }
    public double gbp { get; set; }
    public double hkd { get; set; }
    public double huf { get; set; }
    public double idr { get; set; }
    public double ils { get; set; }
    public double inr { get; set; }
    public double jpy { get; set; }
    public double krw { get; set; }
    public double kwd { get; set; }
    public double lkr { get; set; }
    public double ltc { get; set; }
    public double mmk { get; set; }
    public double mxn { get; set; }
    public double myr { get; set; }
    public double ngn { get; set; }
    public double nok { get; set; }
    public double nzd { get; set; }
    public double php { get; set; }
    public double pkr { get; set; }
    public double pln { get; set; }
    public double rub { get; set; }
    public double sar { get; set; }
    public double sek { get; set; }
    public double sgd { get; set; }
    public double thb { get; set; }
    public double @try { get; set; }
    public double twd { get; set; }
    public double uah { get; set; }
    public double usd { get; set; }
    public double vef { get; set; }
    public double vnd { get; set; }
    public double xag { get; set; }
    public double xau { get; set; }
    public double xdr { get; set; }
    public double xlm { get; set; }
    public double xrp { get; set; }
    public double yfi { get; set; }
    public double zar { get; set; }
    public double bits { get; set; }
    public double link { get; set; }
    public double sats { get; set; }
}

public class PriceChangePercentage60dInCurrency
{
    public double aed { get; set; }
    public double ars { get; set; }
    public double aud { get; set; }
    public double bch { get; set; }
    public double bdt { get; set; }
    public double bhd { get; set; }
    public double bmd { get; set; }
    public double bnb { get; set; }
    public double brl { get; set; }
    public double btc { get; set; }
    public double cad { get; set; }
    public double chf { get; set; }
    public double clp { get; set; }
    public double cny { get; set; }
    public double czk { get; set; }
    public double dkk { get; set; }
    public double dot { get; set; }
    public double eos { get; set; }
    public double eth { get; set; }
    public double eur { get; set; }
    public double gbp { get; set; }
    public double hkd { get; set; }
    public double huf { get; set; }
    public double idr { get; set; }
    public double ils { get; set; }
    public double inr { get; set; }
    public double jpy { get; set; }
    public double krw { get; set; }
    public double kwd { get; set; }
    public double lkr { get; set; }
    public double ltc { get; set; }
    public double mmk { get; set; }
    public double mxn { get; set; }
    public double myr { get; set; }
    public double ngn { get; set; }
    public double nok { get; set; }
    public double nzd { get; set; }
    public double php { get; set; }
    public double pkr { get; set; }
    public double pln { get; set; }
    public double rub { get; set; }
    public double sar { get; set; }
    public double sek { get; set; }
    public double sgd { get; set; }
    public double thb { get; set; }
    public double @try { get; set; }
    public double twd { get; set; }
    public double uah { get; set; }
    public double usd { get; set; }
    public double vef { get; set; }
    public double vnd { get; set; }
    public double xag { get; set; }
    public double xau { get; set; }
    public double xdr { get; set; }
    public double xlm { get; set; }
    public double xrp { get; set; }
    public double yfi { get; set; }
    public double zar { get; set; }
    public double bits { get; set; }
    public double link { get; set; }
    public double sats { get; set; }
}

public class PriceChangePercentage7dInCurrency
{
    public double aed { get; set; }
    public double ars { get; set; }
    public double aud { get; set; }
    public double bch { get; set; }
    public double bdt { get; set; }
    public double bhd { get; set; }
    public double bmd { get; set; }
    public double bnb { get; set; }
    public double brl { get; set; }
    public double btc { get; set; }
    public double cad { get; set; }
    public double chf { get; set; }
    public double clp { get; set; }
    public double cny { get; set; }
    public double czk { get; set; }
    public double dkk { get; set; }
    public double dot { get; set; }
    public double eos { get; set; }
    public double eth { get; set; }
    public double eur { get; set; }
    public double gbp { get; set; }
    public double hkd { get; set; }
    public double huf { get; set; }
    public double idr { get; set; }
    public double ils { get; set; }
    public double inr { get; set; }
    public double jpy { get; set; }
    public double krw { get; set; }
    public double kwd { get; set; }
    public double lkr { get; set; }
    public double ltc { get; set; }
    public double mmk { get; set; }
    public double mxn { get; set; }
    public double myr { get; set; }
    public double ngn { get; set; }
    public double nok { get; set; }
    public double nzd { get; set; }
    public double php { get; set; }
    public double pkr { get; set; }
    public double pln { get; set; }
    public double rub { get; set; }
    public double sar { get; set; }
    public double sek { get; set; }
    public double sgd { get; set; }
    public double thb { get; set; }
    public double @try { get; set; }
    public double twd { get; set; }
    public double uah { get; set; }
    public double usd { get; set; }
    public double vef { get; set; }
    public double vnd { get; set; }
    public double xag { get; set; }
    public double xau { get; set; }
    public double xdr { get; set; }
    public double xlm { get; set; }
    public double xrp { get; set; }
    public double yfi { get; set; }
    public double zar { get; set; }
    public double bits { get; set; }
    public double link { get; set; }
    public double sats { get; set; }
}

public class PublicdoubleerestStats
{
    public double alexa_rank { get; set; }
    public object bing_matches { get; set; }
}

public class ReposUrl
{
    public List<string> github { get; set; }
    public List<object> bitbucket { get; set; }
}

public class CurrentCoin
{
    public string id { get; set; }
    public string symbol { get; set; }
    public string name { get; set; }
    public object asset_platform_id { get; set; }
    public Platforms platforms { get; set; }
    public double block_time_in_minutes { get; set; }
    public string hashing_algorithm { get; set; }
    public List<string> categories { get; set; }
    public object public_notice { get; set; }
    public List<object> additional_notices { get; set; }
    public Description description { get; set; }
    public Links links { get; set; }
    public Image image { get; set; }
    public string country_origin { get; set; }
    public string genesis_date { get; set; }
    public double sentiment_votes_up_percentage { get; set; }
    public double sentiment_votes_down_percentage { get; set; }
    public double market_cap_rank { get; set; }
    public double coingecko_rank { get; set; }
    public double coingecko_score { get; set; }
    public double developer_score { get; set; }
    public double community_score { get; set; }
    public double liquidity_score { get; set; }
    public double public_doubleerest_score { get; set; }
    public MarketData market_data { get; set; }
    public PublicdoubleerestStats public_doubleerest_stats { get; set; }
    public List<object> status_updates { get; set; }
    public DateTime last_updated { get; set; }
}

public class TotalVolume
{
    public long aed { get; set; }
    public long ars { get; set; }
    public long aud { get; set; }
    public double bch { get; set; }
    public long bdt { get; set; }
    public long bhd { get; set; }
    public long bmd { get; set; }
    public double bnb { get; set; }
    public long brl { get; set; }
    public double btc { get; set; }
    public long cad { get; set; }
    public long chf { get; set; }
    public long clp { get; set; }
    public long cny { get; set; }
    public long czk { get; set; }
    public long dkk { get; set; }
    public long dot { get; set; }
    public long eos { get; set; }
    public double eth { get; set; }
    public long eur { get; set; }
    public long gbp { get; set; }
    public long hkd { get; set; }
    public long huf { get; set; }
    public long idr { get; set; }
    public long ils { get; set; }
    public long inr { get; set; }
    public long jpy { get; set; }
    public long krw { get; set; }
    public long kwd { get; set; }
    public long lkr { get; set; }
    public double ltc { get; set; }
    public long mmk { get; set; }
    public long mxn { get; set; }
    public long myr { get; set; }
    public long ngn { get; set; }
    public long nok { get; set; }
    public long nzd { get; set; }
    public long php { get; set; }
    public long pkr { get; set; }
    public long pln { get; set; }
    public long rub { get; set; }
    public long sar { get; set; }
    public long sek { get; set; }
    public long sgd { get; set; }
    public long thb { get; set; }
    public long @try { get; set; }
    public long twd { get; set; }
    public long uah { get; set; }
    public long usd { get; set; }
    public long vef { get; set; }
    public long vnd { get; set; }
    public long xag { get; set; }
    public double xau { get; set; }
    public long xdr { get; set; }
    public long xlm { get; set; }
    public long xrp { get; set; }
    public double yfi { get; set; }
    public long zar { get; set; }
    public long bits { get; set; }
    public long link { get; set; }
    public long sats { get; set; }
}