version: "3"

services:

  cloud-crypto-microservices-postgres:
    image: debezium/postgres:13-alpine
    environment:
      - POSTGRES_DATABASE=cloud_crypto_portfolio_dev
      - POSTGRES_USER=cloud_crypto_dev
      - POSTGRES_PASSWORD=cloud_crypto_dev
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/data/db

volumes:
  postgres-data: