// <auto-generated />
using System;
using System.Collections.Generic;
using Microservice.Report.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Microservice.Report.Migrations
{
    [DbContext(typeof(ReportDbContext))]
    partial class ReportDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microservice.Report.DataAccess.Report", b =>
                {
                    b.Property<Guid>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AssetCount")
                        .HasColumnType("integer");

                    b.Property<List<string>>("AssetList")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<List<float>>("AssetPerformanceAbsolute")
                        .IsRequired()
                        .HasColumnType("real[]");

                    b.Property<List<float>>("AssetPerformancePercentage")
                        .IsRequired()
                        .HasColumnType("real[]");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HighestPerformanceAsset")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LowestPerformanceAsset")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Portfolioname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<float>("WinLossRatioAbsolute")
                        .HasColumnType("real");

                    b.Property<float>("WinLossRatioPercentage")
                        .HasColumnType("real");

                    b.HasKey("ReportId");

                    b.ToTable("report", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
